//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "SharesBrokeringWSPortBinding", Namespace = "http://SharesBrokeringWS/")]
public partial class SharesAcquisitionProxy : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback GetTotalOperationCompleted;

    private System.Threading.SendOrPostCallback BuyShareOperationCompleted;

    private System.Threading.SendOrPostCallback ListCompaniesOperationCompleted;

    private System.Threading.SendOrPostCallback GetCurrencyCodesOperationCompleted;

    private System.Threading.SendOrPostCallback CreateUserOperationCompleted;

    private System.Threading.SendOrPostCallback ListUserSharesOperationCompleted;

    private System.Threading.SendOrPostCallback SellShareOperationCompleted;

    private System.Threading.SendOrPostCallback helloOperationCompleted;

    private System.Threading.SendOrPostCallback CheckUserExistsOperationCompleted;

    private System.Threading.SendOrPostCallback GetUserCurrencyOperationCompleted;

    private System.Threading.SendOrPostCallback GetUserAmountOperationCompleted;

    /// <remarks/>
    public SharesAcquisitionProxy()
    {
        this.Url = "http://192.168.0.7:8080/SharesBrokeringService/SharesBrokeringWS";
    }

    /// <remarks/>
    public event GetTotalCompletedEventHandler GetTotalCompleted;

    /// <remarks/>
    public event BuyShareCompletedEventHandler BuyShareCompleted;

    /// <remarks/>
    public event ListCompaniesCompletedEventHandler ListCompaniesCompleted;

    /// <remarks/>
    public event GetCurrencyCodesCompletedEventHandler GetCurrencyCodesCompleted;

    /// <remarks/>
    public event CreateUserCompletedEventHandler CreateUserCompleted;

    /// <remarks/>
    public event ListUserSharesCompletedEventHandler ListUserSharesCompleted;

    /// <remarks/>
    public event SellShareCompletedEventHandler SellShareCompleted;

    /// <remarks/>
    public event helloCompletedEventHandler helloCompleted;

    /// <remarks/>
    public event CheckUserExistsCompletedEventHandler CheckUserExistsCompleted;

    /// <remarks/>
    public event GetUserCurrencyCompletedEventHandler GetUserCurrencyCompleted;

    /// <remarks/>
    public event GetUserAmountCompletedEventHandler GetUserAmountCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GetTotal([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string shareQty, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string sharePrice, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string currency1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string currency2)
    {
        object[] results = this.Invoke("GetTotal", new object[] {
                    shareQty,
                    sharePrice,
                    currency1,
                    currency2});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetTotal(string shareQty, string sharePrice, string currency1, string currency2, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetTotal", new object[] {
                    shareQty,
                    sharePrice,
                    currency1,
                    currency2}, callback, asyncState);
    }

    /// <remarks/>
    public string EndGetTotal(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void GetTotalAsync(string shareQty, string sharePrice, string currency1, string currency2)
    {
        this.GetTotalAsync(shareQty, sharePrice, currency1, currency2, null);
    }

    /// <remarks/>
    public void GetTotalAsync(string shareQty, string sharePrice, string currency1, string currency2, object userState)
    {
        if ((this.GetTotalOperationCompleted == null))
        {
            this.GetTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTotalOperationCompleted);
        }
        this.InvokeAsync("GetTotal", new object[] {
                    shareQty,
                    sharePrice,
                    currency1,
                    currency2}, this.GetTotalOperationCompleted, userState);
    }

    private void OnGetTotalOperationCompleted(object arg)
    {
        if ((this.GetTotalCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTotalCompleted(this, new GetTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public companyType[] BuyShare([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string Symbol, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string shareQty, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string user)
    {
        object[] results = this.Invoke("BuyShare", new object[] {
                    Symbol,
                    shareQty,
                    user});
        return ((companyType[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginBuyShare(string Symbol, string shareQty, string user, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("BuyShare", new object[] {
                    Symbol,
                    shareQty,
                    user}, callback, asyncState);
    }

    /// <remarks/>
    public companyType[] EndBuyShare(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((companyType[])(results[0]));
    }

    /// <remarks/>
    public void BuyShareAsync(string Symbol, string shareQty, string user)
    {
        this.BuyShareAsync(Symbol, shareQty, user, null);
    }

    /// <remarks/>
    public void BuyShareAsync(string Symbol, string shareQty, string user, object userState)
    {
        if ((this.BuyShareOperationCompleted == null))
        {
            this.BuyShareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyShareOperationCompleted);
        }
        this.InvokeAsync("BuyShare", new object[] {
                    Symbol,
                    shareQty,
                    user}, this.BuyShareOperationCompleted, userState);
    }

    private void OnBuyShareOperationCompleted(object arg)
    {
        if ((this.BuyShareCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.BuyShareCompleted(this, new BuyShareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public companyType[] ListCompanies()
    {
        object[] results = this.Invoke("ListCompanies", new object[0]);
        return ((companyType[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginListCompanies(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ListCompanies", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public companyType[] EndListCompanies(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((companyType[])(results[0]));
    }

    /// <remarks/>
    public void ListCompaniesAsync()
    {
        this.ListCompaniesAsync(null);
    }

    /// <remarks/>
    public void ListCompaniesAsync(object userState)
    {
        if ((this.ListCompaniesOperationCompleted == null))
        {
            this.ListCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCompaniesOperationCompleted);
        }
        this.InvokeAsync("ListCompanies", new object[0], this.ListCompaniesOperationCompleted, userState);
    }

    private void OnListCompaniesOperationCompleted(object arg)
    {
        if ((this.ListCompaniesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ListCompaniesCompleted(this, new ListCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] GetCurrencyCodes()
    {
        object[] results = this.Invoke("GetCurrencyCodes", new object[0]);
        return ((string[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetCurrencyCodes(System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetCurrencyCodes", new object[0], callback, asyncState);
    }

    /// <remarks/>
    public string[] EndGetCurrencyCodes(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }

    /// <remarks/>
    public void GetCurrencyCodesAsync()
    {
        this.GetCurrencyCodesAsync(null);
    }

    /// <remarks/>
    public void GetCurrencyCodesAsync(object userState)
    {
        if ((this.GetCurrencyCodesOperationCompleted == null))
        {
            this.GetCurrencyCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrencyCodesOperationCompleted);
        }
        this.InvokeAsync("GetCurrencyCodes", new object[0], this.GetCurrencyCodesOperationCompleted, userState);
    }

    private void OnGetCurrencyCodesOperationCompleted(object arg)
    {
        if ((this.GetCurrencyCodesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCurrencyCodesCompleted(this, new GetCurrencyCodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void CreateUser([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2)
    {
        this.Invoke("CreateUser", new object[] {
                    arg0,
                    arg1,
                    arg2});
    }

    /// <remarks/>
    public System.IAsyncResult BeginCreateUser(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CreateUser", new object[] {
                    arg0,
                    arg1,
                    arg2}, callback, asyncState);
    }

    /// <remarks/>
    public void EndCreateUser(System.IAsyncResult asyncResult)
    {
        this.EndInvoke(asyncResult);
    }

    /// <remarks/>
    public void CreateUserAsync(string arg0, string arg1, string arg2)
    {
        this.CreateUserAsync(arg0, arg1, arg2, null);
    }

    /// <remarks/>
    public void CreateUserAsync(string arg0, string arg1, string arg2, object userState)
    {
        if ((this.CreateUserOperationCompleted == null))
        {
            this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
        }
        this.InvokeAsync("CreateUser", new object[] {
                    arg0,
                    arg1,
                    arg2}, this.CreateUserOperationCompleted, userState);
    }

    private void OnCreateUserOperationCompleted(object arg)
    {
        if ((this.CreateUserCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public companyType1[] ListUserShares([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0)
    {
        object[] results = this.Invoke("ListUserShares", new object[] {
                    arg0});
        return ((companyType1[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginListUserShares(string arg0, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("ListUserShares", new object[] {
                    arg0}, callback, asyncState);
    }

    /// <remarks/>
    public companyType1[] EndListUserShares(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((companyType1[])(results[0]));
    }

    /// <remarks/>
    public void ListUserSharesAsync(string arg0)
    {
        this.ListUserSharesAsync(arg0, null);
    }

    /// <remarks/>
    public void ListUserSharesAsync(string arg0, object userState)
    {
        if ((this.ListUserSharesOperationCompleted == null))
        {
            this.ListUserSharesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListUserSharesOperationCompleted);
        }
        this.InvokeAsync("ListUserShares", new object[] {
                    arg0}, this.ListUserSharesOperationCompleted, userState);
    }

    private void OnListUserSharesOperationCompleted(object arg)
    {
        if ((this.ListUserSharesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ListUserSharesCompleted(this, new ListUserSharesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public companyType[] SellShare([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string userName, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string companySymbol, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string shareQty)
    {
        object[] results = this.Invoke("SellShare", new object[] {
                    userName,
                    companySymbol,
                    shareQty});
        return ((companyType[])(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginSellShare(string userName, string companySymbol, string shareQty, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("SellShare", new object[] {
                    userName,
                    companySymbol,
                    shareQty}, callback, asyncState);
    }

    /// <remarks/>
    public companyType[] EndSellShare(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((companyType[])(results[0]));
    }

    /// <remarks/>
    public void SellShareAsync(string userName, string companySymbol, string shareQty)
    {
        this.SellShareAsync(userName, companySymbol, shareQty, null);
    }

    /// <remarks/>
    public void SellShareAsync(string userName, string companySymbol, string shareQty, object userState)
    {
        if ((this.SellShareOperationCompleted == null))
        {
            this.SellShareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellShareOperationCompleted);
        }
        this.InvokeAsync("SellShare", new object[] {
                    userName,
                    companySymbol,
                    shareQty}, this.SellShareOperationCompleted, userState);
    }

    private void OnSellShareOperationCompleted(object arg)
    {
        if ((this.SellShareCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SellShareCompleted(this, new SellShareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hello([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string name)
    {
        object[] results = this.Invoke("hello", new object[] {
                    name});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult Beginhello(string name, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("hello", new object[] {
                    name}, callback, asyncState);
    }

    /// <remarks/>
    public string Endhello(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void helloAsync(string name)
    {
        this.helloAsync(name, null);
    }

    /// <remarks/>
    public void helloAsync(string name, object userState)
    {
        if ((this.helloOperationCompleted == null))
        {
            this.helloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhelloOperationCompleted);
        }
        this.InvokeAsync("hello", new object[] {
                    name}, this.helloOperationCompleted, userState);
    }

    private void OnhelloOperationCompleted(object arg)
    {
        if ((this.helloCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.helloCompleted(this, new helloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool CheckUserExists([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
    {
        object[] results = this.Invoke("CheckUserExists", new object[] {
                    arg0,
                    arg1});
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginCheckUserExists(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("CheckUserExists", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }

    /// <remarks/>
    public bool EndCheckUserExists(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }

    /// <remarks/>
    public void CheckUserExistsAsync(string arg0, string arg1)
    {
        this.CheckUserExistsAsync(arg0, arg1, null);
    }

    /// <remarks/>
    public void CheckUserExistsAsync(string arg0, string arg1, object userState)
    {
        if ((this.CheckUserExistsOperationCompleted == null))
        {
            this.CheckUserExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserExistsOperationCompleted);
        }
        this.InvokeAsync("CheckUserExists", new object[] {
                    arg0,
                    arg1}, this.CheckUserExistsOperationCompleted, userState);
    }

    private void OnCheckUserExistsOperationCompleted(object arg)
    {
        if ((this.CheckUserExistsCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckUserExistsCompleted(this, new CheckUserExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GetUserCurrency([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1)
    {
        object[] results = this.Invoke("GetUserCurrency", new object[] {
                    arg0,
                    arg1});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetUserCurrency(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetUserCurrency", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }

    /// <remarks/>
    public string EndGetUserCurrency(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void GetUserCurrencyAsync(string arg0, string arg1)
    {
        this.GetUserCurrencyAsync(arg0, arg1, null);
    }

    /// <remarks/>
    public void GetUserCurrencyAsync(string arg0, string arg1, object userState)
    {
        if ((this.GetUserCurrencyOperationCompleted == null))
        {
            this.GetUserCurrencyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserCurrencyOperationCompleted);
        }
        this.InvokeAsync("GetUserCurrency", new object[] {
                    arg0,
                    arg1}, this.GetUserCurrencyOperationCompleted, userState);
    }

    private void OnGetUserCurrencyOperationCompleted(object arg)
    {
        if ((this.GetUserCurrencyCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserCurrencyCompleted(this, new GetUserCurrencyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://SharesBrokeringWS/", ResponseNamespace = "http://SharesBrokeringWS/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GetUserAmount([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0)
    {
        object[] results = this.Invoke("GetUserAmount", new object[] {
                    arg0});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginGetUserAmount(string arg0, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("GetUserAmount", new object[] {
                    arg0}, callback, asyncState);
    }

    /// <remarks/>
    public string EndGetUserAmount(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void GetUserAmountAsync(string arg0)
    {
        this.GetUserAmountAsync(arg0, null);
    }

    /// <remarks/>
    public void GetUserAmountAsync(string arg0, object userState)
    {
        if ((this.GetUserAmountOperationCompleted == null))
        {
            this.GetUserAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserAmountOperationCompleted);
        }
        this.InvokeAsync("GetUserAmount", new object[] {
                    arg0}, this.GetUserAmountOperationCompleted, userState);
    }

    private void OnGetUserAmountOperationCompleted(object arg)
    {
        if ((this.GetUserAmountCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserAmountCompleted(this, new GetUserAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.netbeans.org/schema/companyXmlSchema")]
public partial class companyType
{

    private string company_nameField;

    private string company_symbolField;

    private int available_sharesField;

    private priceType share_priceField;

    /// <remarks/>
    public string company_name
    {
        get
        {
            return this.company_nameField;
        }
        set
        {
            this.company_nameField = value;
        }
    }

    /// <remarks/>
    public string company_symbol
    {
        get
        {
            return this.company_symbolField;
        }
        set
        {
            this.company_symbolField = value;
        }
    }

    /// <remarks/>
    public int available_shares
    {
        get
        {
            return this.available_sharesField;
        }
        set
        {
            this.available_sharesField = value;
        }
    }

    /// <remarks/>
    public priceType share_price
    {
        get
        {
            return this.share_priceField;
        }
        set
        {
            this.share_priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://xml.netbeans.org/schema/companyXmlSchema")]
public partial class priceType
{

    private string currencyField;

    private float valueField;

    private string last_updateField;

    /// <remarks/>
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    public float value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    public string last_update
    {
        get
        {
            return this.last_updateField;
        }
        set
        {
            this.last_updateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "priceType", Namespace = "http://xml.netbeans.org/schema/userXmlSchema")]
public partial class priceType1
{

    private float valueField;

    private string last_updateField;

    /// <remarks/>
    public float value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    public string last_update
    {
        get
        {
            return this.last_updateField;
        }
        set
        {
            this.last_updateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "companyType", Namespace = "http://xml.netbeans.org/schema/userXmlSchema")]
public partial class companyType1
{

    private string companyNameField;

    private string companySymbolField;

    private int sharesPurchasedField;

    private priceType1 share_priceField;

    /// <remarks/>
    public string companyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
        }
    }

    /// <remarks/>
    public string companySymbol
    {
        get
        {
            return this.companySymbolField;
        }
        set
        {
            this.companySymbolField = value;
        }
    }

    /// <remarks/>
    public int sharesPurchased
    {
        get
        {
            return this.sharesPurchasedField;
        }
        set
        {
            this.sharesPurchasedField = value;
        }
    }

    /// <remarks/>
    public priceType1 share_price
    {
        get
        {
            return this.share_priceField;
        }
        set
        {
            this.share_priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetTotalCompletedEventHandler(object sender, GetTotalCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void BuyShareCompletedEventHandler(object sender, BuyShareCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BuyShareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal BuyShareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public companyType[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((companyType[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ListCompaniesCompletedEventHandler(object sender, ListCompaniesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ListCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal ListCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public companyType[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((companyType[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetCurrencyCodesCompletedEventHandler(object sender, GetCurrencyCodesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCurrencyCodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetCurrencyCodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CreateUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ListUserSharesCompletedEventHandler(object sender, ListUserSharesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ListUserSharesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal ListUserSharesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public companyType1[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((companyType1[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void SellShareCompletedEventHandler(object sender, SellShareCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SellShareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal SellShareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public companyType[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((companyType[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void helloCompletedEventHandler(object sender, helloCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class helloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal helloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CheckUserExistsCompletedEventHandler(object sender, CheckUserExistsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckUserExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal CheckUserExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public bool Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetUserCurrencyCompletedEventHandler(object sender, GetUserCurrencyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserCurrencyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetUserCurrencyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetUserAmountCompletedEventHandler(object sender, GetUserAmountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal GetUserAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
